/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing EventHandler
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventHandlerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventHandler
        //private EventHandler instance;

        public EventHandlerTests()
        {
            // TODO uncomment below to create an instance of EventHandler
            //instance = new EventHandler();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventHandler
        /// </summary>
        [Fact]
        public void EventHandlerInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventHandler
            //Assert.IsType<EventHandler>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'VarEvent'
        /// </summary>
        [Fact]
        public void VarEventTest()
        {
            // TODO unit test for the property 'VarEvent'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'EvaluatorType'
        /// </summary>
        [Fact]
        public void EvaluatorTypeTest()
        {
            // TODO unit test for the property 'EvaluatorType'
        }
    }
}
