/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing Health
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Health
        //private Health instance;

        public HealthTests()
        {
            // TODO uncomment below to create an instance of Health
            //instance = new Health();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Health
        /// </summary>
        [Fact]
        public void HealthInstanceTest()
        {
            // TODO uncomment below to test "IsType" Health
            //Assert.IsType<Health>(instance);
        }

        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }
    }
}
