/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing HealthCheckStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthCheckStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthCheckStatus
        //private HealthCheckStatus instance;

        public HealthCheckStatusTests()
        {
            // TODO uncomment below to create an instance of HealthCheckStatus
            //instance = new HealthCheckStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthCheckStatus
        /// </summary>
        [Fact]
        public void HealthCheckStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthCheckStatus
            //Assert.IsType<HealthCheckStatus>(instance);
        }

        /// <summary>
        /// Test the property 'HealthResults'
        /// </summary>
        [Fact]
        public void HealthResultsTest()
        {
            // TODO unit test for the property 'HealthResults'
        }

        /// <summary>
        /// Test the property 'SuppressedHealthResults'
        /// </summary>
        [Fact]
        public void SuppressedHealthResultsTest()
        {
            // TODO unit test for the property 'SuppressedHealthResults'
        }

        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }
    }
}
