/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing SkipTaskRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SkipTaskRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SkipTaskRequest
        //private SkipTaskRequest instance;

        public SkipTaskRequestTests()
        {
            // TODO uncomment below to create an instance of SkipTaskRequest
            //instance = new SkipTaskRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SkipTaskRequest
        /// </summary>
        [Fact]
        public void SkipTaskRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SkipTaskRequest
            //Assert.IsType<SkipTaskRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TaskInput'
        /// </summary>
        [Fact]
        public void TaskInputTest()
        {
            // TODO unit test for the property 'TaskInput'
        }

        /// <summary>
        /// Test the property 'TaskOutput'
        /// </summary>
        [Fact]
        public void TaskOutputTest()
        {
            // TODO unit test for the property 'TaskOutput'
        }
    }
}
