/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing TaskMock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskMockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskMock
        //private TaskMock instance;

        public TaskMockTests()
        {
            // TODO uncomment below to create an instance of TaskMock
            //instance = new TaskMock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskMock
        /// </summary>
        [Fact]
        public void TaskMockInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskMock
            //Assert.IsType<TaskMock>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Fact]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }

        /// <summary>
        /// Test the property 'ExecutionTime'
        /// </summary>
        [Fact]
        public void ExecutionTimeTest()
        {
            // TODO unit test for the property 'ExecutionTime'
        }

        /// <summary>
        /// Test the property 'QueueWaitTime'
        /// </summary>
        [Fact]
        public void QueueWaitTimeTest()
        {
            // TODO unit test for the property 'QueueWaitTime'
        }
    }
}
