/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SwiftConductor.Model;
using SwiftConductor.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SwiftConductor.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowTestRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowTestRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowTestRequest
        //private WorkflowTestRequest instance;

        public WorkflowTestRequestTests()
        {
            // TODO uncomment below to create an instance of WorkflowTestRequest
            //instance = new WorkflowTestRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowTestRequest
        /// </summary>
        [Fact]
        public void WorkflowTestRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowTestRequest
            //Assert.IsType<WorkflowTestRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Fact]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }

        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Fact]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }

        /// <summary>
        /// Test the property 'TaskToDomain'
        /// </summary>
        [Fact]
        public void TaskToDomainTest()
        {
            // TODO unit test for the property 'TaskToDomain'
        }

        /// <summary>
        /// Test the property 'WorkflowDef'
        /// </summary>
        [Fact]
        public void WorkflowDefTest()
        {
            // TODO unit test for the property 'WorkflowDef'
        }

        /// <summary>
        /// Test the property 'ExternalInputPayloadStoragePath'
        /// </summary>
        [Fact]
        public void ExternalInputPayloadStoragePathTest()
        {
            // TODO unit test for the property 'ExternalInputPayloadStoragePath'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'TaskRefToMockOutput'
        /// </summary>
        [Fact]
        public void TaskRefToMockOutputTest()
        {
            // TODO unit test for the property 'TaskRefToMockOutput'
        }

        /// <summary>
        /// Test the property 'SubWorkflowTestRequest'
        /// </summary>
        [Fact]
        public void SubWorkflowTestRequestTest()
        {
            // TODO unit test for the property 'SubWorkflowTestRequest'
        }
    }
}
