/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using SwiftConductor.Client;
using SwiftConductor.Api;
// uncomment below to import models
//using SwiftConductor.Model;

namespace SwiftConductor.Test.Api
{
    /// <summary>
    ///  Class for testing HealthCheckResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HealthCheckResourceApiTests : IDisposable
    {
        private HealthCheckResourceApi instance;

        public HealthCheckResourceApiTests()
        {
            instance = new HealthCheckResourceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthCheckResourceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HealthCheckResourceApi
            //Assert.IsType<HealthCheckResourceApi>(instance);
        }

        /// <summary>
        /// Test DoCheck
        /// </summary>
        [Fact]
        public void DoCheckTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DoCheck();
            //Assert.IsType<HealthCheckStatus>(response);
        }
    }
}
