name: Docker Build

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: DockerBuild
        run: >
          docker build -f csharp-examples/Dockerfile . -t swift-conductor/conductor-csharp-examples:latest
